name: OpenInsight Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install PyTorch for CPU first
        pip install torch==2.0.1 --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
        pip install -e . # Install OpenInsight in editable mode
        pip install pytest ruff # Dev dependencies for CI

    - name: Lint with Ruff
      run: ruff check .

    - name: Test with Pytest
      run: pytest 